#include<stdio.h>

int main()
{
	char maze[5][5] = {
	{'S', 'O', 'O', 'W', 'W'},
	{'O', 'W', 'O', 'O', 'W'},
	{'O', 'O', 'O', 'W', 'O'},
	{'W', 'W', 'O', 'W', 'O'},
	{'W', 'W', 'O', 'E', 'W'}
	};


	int i,j;
	printf("0,0\t");
	for(i=0;i<5;i++)
	{
		for(j=0;j<5;j++)
		{
			if(maze[i+1][j]=='O')
			{
				printf("%d,%d\t",i+1,j);
				i=i+1;
				if(maze[i][j+1]=='O')
				{
					printf("%d,%d\t",i,j+1);
					j=j+1;
					if(maze[i][j]=='E')
					{
						printf("4,3");
						i=5;
						j=5;
					}
				}
				if(maze[i+1][j]=='O')
				{
					printf("%d,%d\t",i+1,j);
					i=i+1;
					if(maze[i][j+1]=='O')
					{
						printf("%d,%d\t",i,j+1);
						j=j+1;
						if(maze[i][j]=='E')
						{
							printf("4,3");
							i=5;
							j=5;
						}
					}
				}
				if(maze[i][j+1]=='O')
				{
					printf("%d,%d\t",i,j+1);
					j=j+1;
					if(maze[i][j]=='E')
					{
						printf("4,3");
						i=5;
						j=5;
					}
				}
				if(maze[i+1][j]=='O')
				{
					printf("%d,%d\t",i+1,j);
					i=i+1;
					if(maze[i][j+1]=='O')
					{
						printf("%d,%d\t",i,j+1);
						j=j+1;
						if(maze[i][j]=='E')
						{
							printf("4,3");
							i=5;
							j=5;
						}
					}
				}
				if(maze[i][j+1]=='O')
				{
					printf("%d,%d\t",i,j+1);
					j=j+1;
					if(maze[i][j]=='E')
					{
						printf("4,3");
						i=5;
						j=5;
					}
				}
				if(maze[i+1][j]=='O')
				{
					printf("%d,%d\t",i+1,j);
					i=i+1;
					if(maze[i][j+1]=='O')
					{
						printf("%d,%d\t",i,j+1);
						j=j+1;
						if(maze[i][j]=='E')
						{
							printf("4,3");
							i=5;
							j=5;
						}
					}
				}
				if(maze[i][j+1]=='O')
				{
					printf("%d,%d\t",i,j+1);
					j=j+1;
					if(maze[i][j]=='E')
					{
						printf("4,3");
						i=5;
						j=5;
					}
				}
				if(maze[i+1][j]=='O')
				{
					printf("%d,%d\t",i+1,j);
					i=i+1;
					if(maze[i][j+1]=='O')
					{
						printf("%d,%d\t",i,j+1);
						j=j+1;
						if(maze[i][j]=='E')
						{
							printf("4,3");
							i=5;
							j=5;
						}
					}
				}
				if(maze[i][j+1]=='O')
				{
					printf("%d,%d\t",i,j+1);
					j=j+1;
					if(maze[i][j]=='E')
					{
						printf("4,3");
						i=5;
						j=5;
					}
				}
				if(maze[i+1][j]=='O')
				{
					printf("%d,%d\t",i+1,j);
					i=i+1;
					if(maze[i][j+1]=='O')
					{
						printf("%d,%d\t",i,j+1);
						j=j+1;
						if(maze[i][j]=='E')
						{
							printf("4,3");
							i=5;
							j=5;
						}
					}
				}
				if(maze[i][j+1]=='O')
				{
					printf("%d,%d\t",i,j+1);
					j=j+1;
					if(maze[i][j]=='E')
					{
						printf("4,3");
						i=5;
						j=5;
					}
				}
				if(maze[i+1][j]=='O')
				{
					printf("%d,%d\t",i+1,j);
					i=i+1;
					if(maze[i][j+1]=='O')
					{
						printf("%d,%d\t",i,j+1);
						j=j+1;
						if(maze[i][j]=='E')
						{
							printf("4,3");
							i=5;
							j=5;
						}
					}
				}
				if(maze[i][j+1]=='O')
				{
					printf("%d,%d\t",i,j+1);
					j=j+1;
					if(maze[i][j]=='E')
					{
						printf("4,3");
						i=5;
						j=5;
					}
				}
				if(maze[i+1][j]=='O')
				{
					printf("%d,%d\t",i+1,j);
					i=i+1;
					if(maze[i][j+1]=='O')
					{
						printf("%d,%d\t",i,j+1);
						j=j+1;
						if(maze[i][j]=='E')
						{
							printf("4,3");
							i=5;
							j=5;
						}
					}
				}
				if(maze[i][j+1]=='O')
				{
					printf("%d,%d\t",i,j+1);
					j=j+1;
					if(maze[i][j]=='E')
					{
						printf("4,3");
						i=5;
						j=5;
					}
				}
				if(maze[i+1][j]=='O')
				{
					printf("%d,%d\t",i+1,j);
					i=i+1;
					if(maze[i][j+1]=='O')
					{
						printf("%d,%d\t",i,j+1);
						j=j+1;
						if(maze[i][j]=='E')
						{
							printf("4,3");
							i=5;
							j=5;
						}
					}
				}
					
				
			}
		}
	}
	printf("4,3");
}
